# Generated by Django 5.0 on 2023-12-21 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=255, verbose_name="First name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=255, verbose_name="Last name"),
                ),
                ("height", models.IntegerField(verbose_name="Height")),
                ("weight", models.IntegerField(verbose_name="Weight")),
                (
                    "phone_number",
                    models.CharField(max_length=14, verbose_name="Phone number"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "family_status",
                    models.CharField(
                        choices=[
                            ("married", "Married"),
                            ("single", "Single"),
                            ("divorced", "Divorced"),
                        ],
                        max_length=255,
                        verbose_name="Family Status",
                    ),
                ),
                ("birth_date", models.DateField(verbose_name="Birth date")),
                ("address", models.CharField(max_length=255, verbose_name="Address")),
                (
                    "requested_position",
                    models.CharField(max_length=255, verbose_name="Requested position"),
                ),
                (
                    "user_photo",
                    models.ImageField(
                        upload_to="user_photos/", verbose_name="User Photo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Job application",
                "verbose_name_plural": "Job applications",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Full name"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=255, verbose_name="Phone number"),
                ),
                (
                    "telegram_id",
                    models.IntegerField(unique=True, verbose_name="Telegram ID"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Is active"),
                ),
                (
                    "registered_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Registered at"
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_date", models.DateField(verbose_name="Start date")),
                ("finished_date", models.DateField(verbose_name="Finish date")),
                (
                    "employer_name",
                    models.CharField(max_length=255, verbose_name="Employer name"),
                ),
                (
                    "employer_address",
                    models.CharField(max_length=255, verbose_name="Employer Address"),
                ),
                ("position", models.CharField(max_length=255, verbose_name="Position")),
                ("country", models.CharField(max_length=255, verbose_name="Country")),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences",
                        to="bot.jobapplication",
                        verbose_name="Application",
                    ),
                ),
            ],
            options={
                "verbose_name": "Experience",
                "verbose_name_plural": "Experiences",
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_date", models.DateField(verbose_name="Start date")),
                ("finished_date", models.DateField(verbose_name="Finish date")),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "direction",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Direction"
                    ),
                ),
                ("country", models.CharField(max_length=255, verbose_name="Country")),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="educations",
                        to="bot.jobapplication",
                        verbose_name="Application",
                    ),
                ),
            ],
            options={
                "verbose_name": "Education",
                "verbose_name_plural": "Educations",
            },
        ),
        migrations.CreateModel(
            name="ComputerSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "degree",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        max_length=255,
                        verbose_name="Degree",
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="computer_skills",
                        to="bot.jobapplication",
                        verbose_name="Application",
                    ),
                ),
            ],
            options={
                "verbose_name": "Computer skill",
                "verbose_name_plural": "Computer skills",
            },
        ),
        migrations.CreateModel(
            name="ApplicantDoc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("certificate", "Certificate"),
                            ("diploma", "Diploma"),
                        ],
                        max_length=255,
                        verbose_name="Type",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="applicant_docs/", verbose_name="File"),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="docs",
                        to="bot.jobapplication",
                        verbose_name="Application",
                    ),
                ),
            ],
            options={
                "verbose_name": "Applicant doc",
                "verbose_name_plural": "Applicant docs",
            },
        ),
        migrations.CreateModel(
            name="LanguageSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "speaking",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        max_length=255,
                        verbose_name="Speaking",
                    ),
                ),
                (
                    "reading",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        max_length=255,
                        verbose_name="Reading",
                    ),
                ),
                (
                    "writing",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        max_length=255,
                        verbose_name="Writing",
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="language_skills",
                        to="bot.jobapplication",
                        verbose_name="Application",
                    ),
                ),
            ],
            options={
                "verbose_name": "Language skill",
                "verbose_name_plural": "Language skills",
            },
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="bot.user",
                verbose_name="User",
            ),
        ),
        migrations.CreateModel(
            name="VerificationSms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=255, verbose_name="Code")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                ("expires_in", models.DateTimeField(verbose_name="Expires in")),
                ("hit_count", models.IntegerField(default=0, verbose_name="Hit count")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_codes",
                        to="bot.user",
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Verification SMS",
                "verbose_name_plural": "Verification SMSs",
            },
        ),
    ]
