# Generated by Django 5.0 on 2023-12-21 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Text")),
                ("index", models.IntegerField(verbose_name="Index")),
            ],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
            },
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("question_count", models.IntegerField(verbose_name="Question count")),
                (
                    "answer_count_in_question",
                    models.IntegerField(verbose_name="Answer count in question"),
                ),
                ("index", models.IntegerField(verbose_name="Index")),
            ],
            options={
                "verbose_name": "Test",
                "verbose_name_plural": "Tests",
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Text")),
                ("index_format", models.IntegerField(verbose_name="Index format")),
                ("ball", models.IntegerField(verbose_name="Ball")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bot.question",
                        verbose_name="Question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Answer",
                "verbose_name_plural": "Answers",
            },
        ),
        migrations.AddField(
            model_name="question",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="bot.test",
                verbose_name="Test",
            ),
        ),
        migrations.CreateModel(
            name="TotalBallRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_ball", models.IntegerField(verbose_name="From ball")),
                ("to_ball", models.IntegerField(verbose_name="To ball")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bot.test",
                        verbose_name="Test",
                    ),
                ),
            ],
            options={
                "verbose_name": "Total ball range",
                "verbose_name_plural": "Total ball ranges",
            },
        ),
        migrations.CreateModel(
            name="UserTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_finished",
                    models.BooleanField(default=False, verbose_name="Is finished"),
                ),
                ("total_ball", models.IntegerField(verbose_name="Total ball")),
                (
                    "finished_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Finished at"),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_tests",
                        to="bot.test",
                        verbose_name="Test",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_tests",
                        to="bot.user",
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User test",
                "verbose_name_plural": "User tests",
            },
        ),
    ]
