# Generated by Django 5.0 on 2023-12-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0007_alter_jobapplication_height_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="finished_date",
            field=models.CharField(max_length=10, verbose_name="Finish date"),
        ),
        migrations.AlterField(
            model_name="education",
            name="started_date",
            field=models.CharField(max_length=10, verbose_name="Start date"),
        ),
        migrations.AlterField(
            model_name="experience",
            name="finished_date",
            field=models.CharField(max_length=10, verbose_name="Finish date"),
        ),
        migrations.AlterField(
            model_name="experience",
            name="started_date",
            field=models.CharField(max_length=10, verbose_name="Start date"),
        ),
    ]
