# Generated by Django 5.0 on 2023-12-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0009_alter_answer_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertest",
            name="finished_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Finished at"),
        ),
    ]
