class JobApplicationState:
    """State of the job application process."""

    FIRST_NAME = 1
    LAST_NAME = 2
    PHOTO_4X5 = 3
    PHOTO_FULL_BODY = 4
    HEIGHT = 5
    WEIGHT = 6
    PHONE_NUMBER = 7
    EMAIL = 8
    FAMILY_STATUS = 9
    BIRTH_DATE = 10
    ADDRESS = 11
    REQUESTED_POSITION = 12
    APPLICANT_DOC_TYPE = 13
    APPLICANT_DOC = 14
    COMPUTER_SKILL_NAME = 15
    COMPUTER_SKILL_DEGREE = 16
    EDUCATION_TITLE = 17
    EDUCATION_STARTED_DATE = 18
    EDUCATION_FINISHED_DATE = 19
    EDUCATION_DIRECTION = 20
    EDUCATION_COUNTRY = 21
    EXPERIENCE_ORGANIZATION_NAME = 22
    EXPERIENCE_ORGANIZATION_ADDRESS = 23
    EXPERIENCE_POSITION = 24
    EXPERIENCE_STARTED_DATE = 25
    EXPERIENCE_FINISHED_DATE = 26
    EXPERIENCE_COUNTRY = 27
    LANGUAGE_SKILL_NAME = 28
    LANGUAGE_SKILL_SPEAKING = 29
    LANGUAGE_SKILL_READING = 30
    LANGUAGE_SKILL_WRITING = 31
    LANGUAGE_SKILL_LISTENING = 32
    FINISH = 33


class TestState:
    """State of the test process."""

    QUESTION = 1
    ANSWER = 2
    FINISH = 3
